const products = [
  {
    _id: '1',
    sku: 'AC2-UL',
    image: '/images/AC2-UL.jpg',
    description:
      'AC Adapter for Acer Laptops',
    brand: 'PWR+',
    inStock: 0,
    specs: '19V 3.42A',
    connector_size: '5.5x1.7',
    connector_length: '12mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 2.1oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAJ190342',
    status: 0
  },
  {
    _id: '2',
    sku: 'AC3-UL',
    image: '/images/AC3-UL.jpg',
    description:
      'AC Adapter for ASUS Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '19V 3.42A',
    connector_size: '5.5x2.5',
    connector_length: '12mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 1.8oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAJ190342',
    status: 0
  },
  {
    _id: '3',
    sku: 'C22-UL',
    image: '/images/C22-UL.jpg',
    description:
      'AC Adapter for HP Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '19.5V 4.62A',
    connector_size: '4.5x3.0',
    connector_length: '12mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 5.8oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAK195462',
    status: 0
  },
  {
    _id: '4',
    sku: 'C27-UL',
    image: '/images/C27-UL.jpg',
    description:
      'AC Adapter for HP Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '19.5V 3.33A',
    connector_size: '4.5x3.0',
    connector_length: '12mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 1.9oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAK195462',
    status: 0
  },
  {
    _id: '5',
    sku: 'D7-UL',
    image: '/images/D7-UL.jpg',
    description:
      'AC Adapter for Dell Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '19.5V 3.33A',
    connector_size: '4.5x3.0',
    connector_length: '10mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 1.4oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAK195462',
    status: 0
  },
  {
    _id: '6',
    sku: 'HD7-UL',
    image: '/images/HD7-UL.jpg',
    description:
      'AC Adapter for Casio Keyboard',
    brand: 'PWR+',
    inStock: 1,
    specs: '9.5V 1.1A',
    connector_size: '4.7x1.7',
    connector_length: '9.5mm',
    cord_length: '6.6Ft',
    type: 'L',
    weight: '5.2oz',
    box_qty: '80',
    product_dimension: '4.5x3.1x3',
    ul_model: 'PWR-TAK195462',
    status: 0
  },
  {
    _id: '7',
    sku: 'I11-UL',
    image: '/images/I11-UL.jpg',
    description:
      'AC Adapter for Panasonic Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '16V 4.06A',
    connector_size: '5.5x2.5',
    connector_length: '12mm',
    cord_length: '12Ft',
    type: 'S',
    weight: '1lb 1.9oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAK195462',
    status: 0
  },
  {
    _id: '8',
    sku: 'IL12-UL',
    image: '/images/IL12-UL.jpg',
    description:
      'AC Adapter for Lenovo Laptops',
    brand: 'PWR+',
    inStock: 1,
    specs: '20V 3.25A',
    connector_size: '4.0x1.7',
    connector_length: '10mm',
    cord_length: '12Ft',
    type: 'L',
    weight: '1lb 1.8oz',
    box_qty: '30',
    product_dimension: '7x3.5x3.5',
    ul_model: 'PWR-TAK195462',
    status: 0
  }
]

export default products
